# Generated by Django 5.1.7 on 2025-03-25 14:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("dogs", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="breed",
            name="photo",
            field=models.ImageField(
                blank=True,
                help_text="Загрузите фото породы",
                null=True,
                upload_to="breeds/photo",
                verbose_name="Фото породы",
            ),
        ),
    ]
