# Generated by Django 5.1.7 on 2025-03-27 15:38

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("dogs", "0002_breed_photo"),
    ]

    operations = [
        migrations.CreateModel(
            name="Parent",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        help_text="Введите кличку предка собаки",
                        max_length=100,
                        verbose_name="Кличка",
                    ),
                ),
                (
                    "year",
                    models.PositiveIntegerField(
                        default=100,
                        help_text="Укажите год рождения",
                        verbose_name="Год рождения",
                    ),
                ),
                (
                    "breed",
                    models.ForeignKey(
                        blank=True,
                        help_text="Введите породу предка собаки",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="parent_dogs",
                        to="dogs.breed",
                        verbose_name="Порода",
                    ),
                ),
                (
                    "dog",
                    models.ForeignKey(
                        blank=True,
                        help_text="Выберете собаку",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="parent",
                        to="dogs.dogs",
                        verbose_name="Собака",
                    ),
                ),
            ],
            options={
                "verbose_name": "Предок собаки",
                "verbose_name_plural": "Предки собаки",
            },
        ),
    ]
