# Generated by Django 4.2.13 on 2025-04-03 08:08

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("dogs", "0003_parent"),
    ]

    operations = [
        migrations.AddField(
            model_name="dogs",
            name="owner",
            field=models.ForeignKey(
                blank=True,
                help_text="Введите идентификатор владельца собаки",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="user",
                to=settings.AUTH_USER_MODEL,
                verbose_name="Владелец собаки",
            ),
        ),
    ]
